// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in DocuFlow user's profile (username, email, role, group).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("username,email,is_active,group_id").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles ?? []).map((r) => r.role)
    };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-documents.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function clientFor(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_documents_default = defineTool2({
  name: "list_documents",
  title: "List documents",
  description: "List documents the signed-in user can access. Optionally filter by folder path and status.",
  inputSchema: {
    folder: z.string().optional().describe("Folder path filter (exact match), e.g. 'Ressources Humaines/Recrutement'."),
    status: z.enum(["pending", "approved", "draft", "rejected"]).optional(),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ folder, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = clientFor(ctx).from("documents").select("id,name,type,folder,status,version,author,updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (folder) q = q.eq("folder", folder);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { documents: data ?? [] } };
  }
});

// src/lib/mcp/tools/search-documents.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function clientFor2(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_documents_default = defineTool3({
  name: "search_documents",
  title: "Search documents",
  description: "Search documents by name or folder for the signed-in user.",
  inputSchema: {
    query: z2.string().min(1).describe("Search term matched against name and folder."),
    limit: z2.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const like = `%${query}%`;
    const { data, error } = await clientFor2(ctx).from("documents").select("id,name,type,folder,status,author,updated_at").or(`name.ilike.${like},folder.ilike.${like}`).order("updated_at", { ascending: false }).limit(limit);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { results: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-folders.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function clientFor3(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_folders_default = defineTool4({
  name: "list_folders",
  title: "List folders",
  description: "List folders (groups and subfolders) the signed-in user can access.",
  inputSchema: {
    parent_path: z3.string().nullable().optional().describe("Filter by parent path. Pass null for top-level folders.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ parent_path }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = clientFor3(ctx).from("folders").select("id,name,path,parent_path").order("name");
    if (parent_path === null) q = q.is("parent_path", null);
    else if (parent_path) q = q.eq("parent_path", parent_path);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { folders: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-pending-validations.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function clientFor4(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pending_validations_default = defineTool5({
  name: "list_pending_validations",
  title: "List pending validations",
  description: "List documents currently awaiting validation that the signed-in user can see.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await clientFor4(ctx).from("documents").select("id,name,folder,author,updated_at").eq("status", "pending").order("updated_at", { ascending: false }).limit(limit);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { pending: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "satvlvizkiqqgxopvcec";
var mcp_default = defineMcp({
  name: "docuflow-mcp",
  title: "DocuFlow",
  version: "0.1.0",
  instructions: "Tools for the DocuFlow document management app. Use whoami to identify the signed-in user, list_folders to browse the folder tree, list_documents and search_documents to find files, and list_pending_validations to see items awaiting approval. All calls run under the user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_folders_default,
    list_documents_default,
    search_documents_default,
    list_pending_validations_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
